version: "3.8"
services:
  pg:
    build: hack/postgres
    image: rueian/postgres:9.6-logical
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/pgc/postgresql.conf", "-c","hba_file=/pgc/pg_hba.conf"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./hack/postgres:/pgc
  pulsar:
    image: apachepulsar/pulsar:2.6.1
    command: ["bin/pulsar", "standalone"]
    ports:
      - 6650:6650
